services:
  db:
    container_name: nest-db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  
  app:
    build:
      context: .
      target: ${STAGE}
      dockerfile: Dockerfile
    volumes:
      - .:/app/
      - /app/node_modules
    container_name: nest-app
    ports:
      - ${PORT}:${PORT}
    environment:
      STAGE: ${STAGE}
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      APP_VERSION: ${APP_VERSION}

volumes:
  db_data:
    external: false